XP_Scrum_Grupp2/Controllers/CalendarController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XP_Scrum_Grupp2.Models;

namespace XP_Scrum_Grupp2.Controllers
{
    public class CalendarController : BaseController
    {
        public JsonResult GetUEvents()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var userId = User.Identity.GetUserId();
                var events = db.UserEvents.Where(u => u.CreatorId == userId).ToList();
                var me = db.Meetings.Where(m => m.CreatorId == userId || m.Approved == true).ToList();
                var model = new PersonalCalendarViewModel
                {
                    PersonalEvents = events,
                    Meetings = me
                };
                return new JsonResult { Data = model, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }
        public ActionResult ShowInvited(int meetingId)
        {
            var model = db.MeetingInvitees.Where(m => m.MeetingId == meetingId).ToList();
            return PartialView("_Invited", model);
        }

        [HttpPost]
        public JsonResult SaveEvent(UEvent e)
        {
            var user = User.Identity.GetUserId();
            var status = false;
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var curr = db.Users.Where(u => u.Id == user).FirstOrDefault();
                var v = new UEvent
                {
                    Title = e.Title,
                    Start = e.Start,
                    End = e.End,
                    AllDay = e.AllDay,
                    Creator = curr,
                    CreatorId = curr.Id
                };
                db.UserEvents.Add(v);
                db.SaveChanges();
                status = true;
            }
            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public JsonResult DeleteEvent(int eventID)
        {
            var status = false;
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var v = db.UserEvents.Where(a => a.Id == eventID).FirstOrDefault();
                if (v != null)
                {
                    db.UserEvents.Remove(v);
                    db.SaveChanges();
                    status = true;
                }
            }
            return new JsonResult { Data = new { status = status } };
        }

        public ActionResult ShowPersonalCalendar()
        {
            var userId = User.Identity.GetUserId();
            ApplicationDbContext db = new ApplicationDbContext();
            var ue = db.UserEvents.Where(u => u.Creator.Id == userId).ToList();
            var me = db.Meetings.Where(m => m.CreatorId == userId).ToList();
            var model = new PersonalCalendarViewModel
            {
                PersonalEvents = ue,
                Meetings = me
            };
            return View(model);
        }

        public JsonResult GetEvents()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var me = db.Meetings.Where(m=>m.Approved == true).ToList();
                return new JsonResult { Data = me, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
            }
        }
        public ActionResult ShowCalendar()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            var meetings = db.Meetings.Where(m => m.Approved == true).ToList();
            var inviteds = new List<List<MeetingInvited>>
            {
                new List<MeetingInvited>()
            };
            foreach (var m in meetings)
            {
                var o = db.MeetingInvitees.Where(me => me.MeetingId == m.Id).ToList();
                inviteds.Add(o);
            }
            var model = new MeetingInvitedModel {
                Meetinginvited = inviteds
            };
            return View(model);
        }
    }
        public class MeetingInvitedModel
    {
        public List<List<MeetingInvited>> Meetinginvited { get; set; }

    }

    public class Events
    {
        public string id { get; set; }
        public string title { get; set; }
        public string date { get; set; }
        public string start { get; set; }
        public string end { get; set; }
        public string url { get; set; }
        public bool allDay { get; set; }
    }

    public class PersonalCalendarViewModel
    {
        public ICollection<UEvent> PersonalEvents { get; set; }
        public ICollection<Meeting> Meetings { get; set; }
    }
}

XP_Scrum_Grupp2/Views/Calendar/ShowCalendar.cshtml
@model XP_Scrum_Grupp2.Controllers.MeetingInvitedModel
<br />
<br />
<div id="calender" style="max-width:80%;margin-left:8.5%"></div>
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
            </div>
            <div class="modal-body">
                <p id="pDetails"></p>
            </div>
            <p style="font-size: 18px;margin-left:4%">Participants:</p>
                        <p id="name"> </p>
            <div id="invitedPeople"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script>
        $(document).ready(function () {

            var url = '@Url.Action("ShowInvited", "Calendar")';
            $('#calender').click(function () {
                var ID = $('#name').val();
                $('#invitedPeople').load(url, { meetingId: ID });
            });

                var events = [];
                var selectedEvent = null;
                FetchEventAndRenderCalendar();
                function FetchEventAndRenderCalendar() {
                    events = [];
                    $.ajax({
                        type: "GET",
                        url: "/Calendar/GetEvents",
                        success: function (data) {
                            $.each(data, function (i, v) {
                                events.push({
                                    eventID: v.Id,
                                    title: v.Title,
                                    description: v.Description,
                                    start: moment(v.Start),
                                    end: v.End != null ? moment(v.End) : null,
                                    color: "#3a87ad",
                                    allDay: v.AllDay
                                });
                            })
                            GenerateCalender(events);
                        },
                        error: function (error) {
                            alert('failed');
                        }
                    })
                }

                function GenerateCalender(events) {
                    $('#calender').fullCalendar('destroy');
                    $('#calender').fullCalendar({
                        contentHeight: 400,
                        defaultDate: new Date(),
                        timeFormat: 'h(:mm)a',
                        header: {
                            left: 'prev,next today',
                            center: 'title',
                            right: 'month,basicWeek,basicDay,agenda'
                        },
                        eventLimit: true,
                        eventColor: '#378006',
                        events: events,
                        eventClick: function (calEvent, jsEvent, view) {
                            selectedEvent = calEvent;
                            $('#myModal #eventTitle').text(calEvent.title);
                            var $description = $('<div/>');
                            $description.append($('<p/>').html('<b>Start:</b>' + calEvent.start.format("YYYY-MM-DD HH:mm")));
                            if (calEvent.end != null) {
                                $description.append($('<p/>').html('<b>End:</b>' + calEvent.end.format("YYYY-MM-DD HH:mm")));
                            }

                            $('#myModal #pDetails').empty().html($description);
                            $('#myModal #name').val(calEvent.eventID);
                            $('#myModal #invitedPeople').empty();
                            $('#myModal').modal();
                        },
                        selectable: true,
                        select: function (start, end) {
                            selectedEvent = {
                                eventID: 0,
                                title: '',
                                description: '',
                                start: start,
                                end: end,
                                allDay: false,
                                color: ''
                            };
                            openAddEditForm();
                            $('#calendar').fullCalendar('unselect');
                        },
                        editable: false
                    });
                }
            });
     
        </script>
    }
                  

XP_Scrum_Grupp2/Views/Calendar/ShowPersonalCalendar.cshtml
@model XP_Scrum_Grupp2.Controllers.PersonalCalendarViewModel
<br />
<br />
<div id="calender" style="max-width:80%;margin-left:8.5%"></div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
            </div>
            <div class="modal-body">
                <p id="pDetails"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div id="myModalSave" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Create event</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" id="hdEventID" value="0" />
                    <div style="margin-left: 4%" class="form-group">
                        <label>Subject</label>
                        <input type="text" id="txtSubject" class="form-control" />
                    </div>
                    <div style="margin-left: 4%" class="form-group">
                        <label>Start</label>
                        <div class="input-group date" id="dtp1">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                            <input type="text" id="txtStart" class="form-control" />

                        </div>
                    </div>
                    <div class="form-group" style="margin-left:4%" id="divEndDate" >
                        <label>End</label>
                        <div class="input-group date" id="dtp2">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                            <input type="text" id="txtEnd" class="form-control" />
                           
                        </div>
                    </div>
                    <button type="button" id="btnSave" class="btn btn-success">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>

<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script>
        $(document).ready(function () {
            var events = [];
            var selectedEvent = null;
            FetchEventAndRenderCalendar();
            function FetchEventAndRenderCalendar() {
                events = [];
                $.ajax({
                    type: "GET",
                    url: "/Calendar/GetUEvents",
                    success: function (data) {
                        $.each(data.PersonalEvents, function (i, v) {
                            events.push({
                                eventID: v.Id,
                                title: v.Title,
                                description: v.Description,
                                start: moment(v.Start),
                                end: v.End != null ? moment(v.End) : null,
                                color: "palevioletred"
                            });
                        })
                        $.each(data.Meetings, function (i, v) {
                            events.push({
                                eventID: v.Id,
                                title: v.Title,
                                description: v.Description,
                                start: moment(v.Start),
                                end: v.End != null ? moment(v.End) : null,
                                color: "#3a87ad"
                            });
                        })
                        GenerateCalender(events);
                    },
                    error: function (error) {
                        alert('failed');
                    }
                })
            }
            function GenerateCalender(events) {
                $('#calender').fullCalendar('destroy');
                $('#calender').fullCalendar({
                    contentHeight: 450,
                    defaultDate: new Date(),
                    timeFormat: 'h(:mm)a',
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,basicWeek,basicDay,agenda'
                    },
                    eventLimit: true,
                    eventColor: '#378006',
                    events: events,
                    eventClick: function (calEvent, jsEvent, view) {
                        selectedEvent = calEvent;
                        $('#myModal #eventTitle').text(calEvent.title);
                        var $description = $('<div/>');
                        $description.append($('<p/>').html('<b>Start:</b>' + calEvent.start.format("YYYY-MM-DD HH:mm")));
                        if (calEvent.end != null) {
                            $description.append($('<p/>').html('<b>End:</b>' + calEvent.end.format("YYYY-MM-DD HH:mm")));
                        }
                        $('#myModal #pDetails').empty().html($description);

                        $('#myModal').modal();
                    },
                    selectable: true,
                    select: function (start, end) {
                        selectedEvent = {
                            eventID: 0,
                            title: '',
                            description: '',
                            start: start,
                            end: end,
                            allDay: false,
                            color: ''
                        };
                        openAddEditForm();
                        $('#calendar').fullCalendar('unselect');
                    },
                    editable: true,
                    eventDrop: function (event) {
                        var data = {
                            Id: event.eventID,
                            Title: event.title,
                            Start: event.start.format('YYYY-MM-DD HH:mm'),
                            End: event.end != null ? event.end.format('YYYY-MM-DD HH:mm') : null,
                            Description: event.description,
                            ThemeColor: event.color
                        };
                        SaveEvent(data);
                    }
                })
            }

            $('#btnEdit').click(function () {
                //Open modal dialog for edit event
                openAddEditForm();
            })
            $('#btnDelete').click(function () {
                if (selectedEvent != null && confirm('Are you sure?')) {
                    $.ajax({
                        type: "POST",
                        url: '/Calendar/DeleteEvent',
                        data: {'eventID': selectedEvent.eventID},
                        success: function (data) {
                            if (data.status) {
                                //Refresh the calender
                                FetchEventAndRenderCalendar();
                                $('#myModal').modal('hide');
                            }
                        },
                        error: function () {
                            alert('Failed');
                        }
                    })
                }
            })
            $('#dtp1,#dtp2').datetimepicker({
                format: 'YYYY-MM-DD HH:mm'
            });
            $('#chkIsFullDay').change(function () {
                if ($(this).is(':checked')) {
                    $('#divEndDate').hide();
                }
                else {
                    $('#divEndDate').show();
                }
            });
            function openAddEditForm() {
                if (selectedEvent != null) {
                    $('#hdEventID').val(selectedEvent.eventID);
                    $('#txtSubject').val(selectedEvent.title);
                    //$('#txtStart').val(selectedEvent.start.format('DD/MM/YYYY HH:mm A'));
                    $('#txtStart').val(selectedEvent.start.format('YYYY-MM-DD HH:mm'));
                    $('#chkIsFullDay').prop("checked", selectedEvent.allDay || false);
                    $('#chkIsFullDay').change();
                    $('#txtEnd').val(selectedEvent.end != null ? selectedEvent.end.format('YYYY-MM-DD HH:mm') : '');
                    $('#txtDescription').val(selectedEvent.description);
                    $('#ddThemeColor').val(selectedEvent.color);
                }
                $('#myModal').modal('hide');
                $('#myModalSave').modal();
            }
            $('#btnSave').click(function () {

                //Validation/
                if ($('#txtSubject').val().trim() == "") {
                    alert('Title required');
                    return;
                }
                if ($('#txtStart').val().trim() == "") {
                    alert('Start date required');
                    return;
                }
                if ($('#txtEnd').val().trim() == "") {
                    alert('End date required');
                    return;
                }
                else {
                    var startDate = moment($('#txtStart').val(), "YYYY-MM-DD HH:mm").toDate();
                    var endDate = moment($('#txtEnd').val(), "YYYY-MM-DD HH:mm").toDate();
                    if (startDate > endDate) {
                        alert('Invalid end date');
                        return;
                    }
                }

                var data = {
                    Id: $('#hdEventID').val(),
                    Title: $('#txtSubject').val().trim(),
                    Start: $('#txtStart').val().trim(),
                    End:  $('#txtEnd').val().trim(),
                    Description: $('#txtDescription').val(),
                    ThemeColor: $('#ddThemeColor').val()
                }
                SaveEvent(data);
                // call function for submit data to the server
            })
            function SaveEvent(data) {
                $.ajax({
                    type: "POST",
                    url: '/Calendar/SaveEvent',
                    data: data,
                    success: function (data) {
                        if (data.status) {
                            //Refresh the calender
                            FetchEventAndRenderCalendar();
                            $('#myModalSave').modal('hide');
                        }
                    },
                    error: function () {
                        alert('Failed');
                    }
                })
            }
        })
    </script>
}